name: Deploy
on:
  schedule:
    # Run at 6:00 every day
    - cron: '0 6 * * *'
  workflow_dispatch:
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install project
        run: pip install .
      - name: Run rfparser
        run: |
          mkdir outdir
          rfparser -v --xml outdir/pubs_for_website.xml
        env:
          RF_USERNAME: ${{ secrets.RF_USERNAME }}
          RF_PASSWORD: ${{ secrets.RF_PASSWORD }}
          RFPARSER_EMAIL: ${{ secrets.RFPARSER_EMAIL }}
          NBIROS_PUB_EXPORT_XML_URL: ${{ secrets.NBIROS_PUB_EXPORT_XML_URL }}
          PEOPLE_DATA_CSV_URL: ${{ secrets.PEOPLE_DATA_CSV_URL }}
      - name: Upload to 'artifacts' branch
        uses: s0/git-publish-subdir-action@develop
        env:
          BRANCH: artifacts
          FOLDER: outdir
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: self
          SKIP_EMPTY_COMMITS: true
          TARGET_DIR: .
