name: Python linting
on:
  push:
    paths:
      - '**.py'
      - .github/workflows/lint.yaml
      - .flake8
      - .isort.cfg
      - mypy.ini
      - pyproject.toml
      - tox.ini
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/lint.yaml
      - .flake8
      - .isort.cfg
      - mypy.ini
      - pyproject.toml
      - tox.ini
concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Run tox
        run: tox -e lint,mypy
      - uses: psf/black@stable
      - uses: isort/isort-action@v1
