name: Test
on:
  push:
    paths:
      - '**.py'
      - .github/workflows/test.yaml
      - pyproject.toml
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/test.yaml
      - pyproject.toml
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Run unit tests
        run: tox -e test
      - name: Install project
        run: pip install .
      - name: Persist requests-cache's cache file
        uses: actions/cache@v4
        with:
          key: http_cache-${{ github.run_id }}
          path: http_cache.sqlite
          restore-keys: |
            http_cache-
      - name: Test rfparser
        run: rfparser -v --pages 1 --xml pubs_for_website.xml
        env:
          RF_USERNAME: ${{ secrets.RF_USERNAME }}
          RF_PASSWORD: ${{ secrets.RF_PASSWORD }}
          RFPARSER_EMAIL: ${{ secrets.RFPARSER_EMAIL }}
          NBIROS_PUB_EXPORT_XML_URL: ${{ secrets.NBIROS_PUB_EXPORT_XML_URL }}
          PEOPLE_DATA_CSV_URL: ${{ secrets.PEOPLE_DATA_CSV_URL }}
      - uses: actions/upload-artifact@v4
        with:
          name: Pubs for website (${{ matrix.python-version }})
          path: pubs_for_website.xml
